$pt_keys = @(
    'lang="pt-BR"',
    '<title>Oferta Exclusiva</title>',
    "Pedido quase finalizado...",
    "Pedido Quase Finalizado...",
    "ESPERE! Seu pedido ainda não está completo...",
    'Leve o <span style="font-weight: 400;">Audiobook</span>',
    "Receba 3 Bônus Extras",
    "DE GRAÇA!",
    "**Oferta Especial Apenas Para Novos Membros**",
    "Antes de finalizar seu pedido, eu tenho uma pequena pergunta para você...",
    "Você já garantiu nosso guia completo que te mostra exatamente como controlar a sua alimentação",
    ", sem abrir mão dos alimentos que você ama.",
    " após os 60",
    "Mas e se você pudesse absorver tudo com mais facilidade? E se você pudesse, literalmente, <em>escutar</em> o guia por onde quer que fosse, sem precisar forçar a vista ou interromper sua rotina?",
    "Neste momento, você tem a oportunidade exclusiva de aprimorar seu pedido e levar a versão completa em <strong>Audiobook do",
    "Ao invés de precisar encontrar um momento tranquilo para sentar e ler, basta apertar 'play' e começar a absorver imediatamente essas diretrizes transformadoras. Seja enquanto relaxa na poltrona, faz uma caminhada suave ou cuida dos afazeres da casa...",
    "Todo o conteúdo é gravado com uma narração profissional e agradável, para que você adote o melhor estilo de vida saudável sem nenhum esforço.",
    "V 100% Amigável Para Iniciantes & Desenvolvido Para a Terceira Idade",
    "Veja o que você leva por apenas 29 hoje:",
    "Escute em qualquer lugar, a qualquer hora. Perfeito para descansar os olhos e absorver o conhecimento sem estresse.",
    "Bônus #1: Comunidade Privada (Valor 97)",
    "Você não está sozinho(a). Tenha acesso rápido para trocar experiências com quem tem objetivos parecidos com o seu.",
    "Bônus #2: Áudios de Receitas Guiadas (Valor 147)",
    "Escute o passo a passo de receitas incríveis na cozinha, sendo facilmente guiado por todo o processo.",
    "Bônus #3: Acesso Vitalício ao Aplicativo (Valor 19/mês)",
    "Tenha todo o seu guia no bolso. Fácil de mexer, super acessível e hoje totalmente DE GRAÇA.",
    "Essa é uma oferta única.",
    "Assim que você sair desta página, estes bônus sumirão e o Audiobook voltará ao seu preço normal de 197.",
    "Como você é novo(a) por aqui, você adiciona esse pacote completo por um <strong>pagamento único de 29!</strong>",
    "Garantia de Devolução de 30 Dias",
    "Pagamento seguro • Criptografado",
    "Atualização Verificada",
    "Página de Pedido Segura • Política de Privacidade • Termos e Condições",
    "⚠️ NÃO FECHE ESSA PÁGINA!",
    "Leve o Audiobook Com Um <span style=`"color: #B3200B; text-decoration: underline;`">Desconto Exclusivo</span>!",
    "Para tornar esta oferta irresistível, <strong>eu removi o acesso à comunidade privada</strong> (o que reduz meus custos) para entregar a você o <strong>Audiobook Completo das Receitas Proteicas + Áudios de Receitas Passo a Passo</strong>...",
    "Para tornar esta oferta irresistível, <strong>eu removi o acesso à comunidade privada</strong> (o que reduz meus custos) para entregar a você o <strong>Audiobook Completo das Receitas & Meal Prep + Áudios de Receitas Passo a Passo</strong>...",
    "Para tornar esta oferta irresistível, <strong>eu removi o acesso à comunidade privada</strong> (o que reduz meus custos) para entregar a você o <strong>Audiobook Completo para Limpar o Fígado + Áudios de Receitas Passo a Passo</strong>...",
    "Para tornar esta oferta irresistível, <strong>eu removi o acesso à comunidade privada</strong> (o que reduz meus custos) para entregar a você o <strong>Audiobook Completo de Receitas de Diabetes + Áudios de Receitas Passo a Passo</strong>...",
    "Para tornar esta oferta irresistível, <strong>eu removi o acesso à comunidade privada</strong> (o que reduz meus custos) para entregar a você o <strong>Audiobook Completo do Dieta + Áudios de Receitas Passo a Passo</strong>...",
    "Por um pagamento único de apenas 19!",
    "*Clique no botão abaixo para adicionar esse desconto imediato ao seu pedido seguro.",
    '"O audiobook mudou tudo para mim!"',
    '"Minha visão já não é a mesma, então ler na tela era difícil. Este audiobook me permitiu escutar os ensinamentos práticos de como cozinhar proteínas e carboidratos da melhor forma. Preparar as refeições agora ficou super simples!"',
    '"Essas dicas valem cada centavo de 29."',
    '"Eu estava em dúvida, mas as dicas diárias e os áudios são maravilhosos. Escutar as receitas em vez de ler mudou minha rotina. As receitas com alto teor de proteína me deram muita energia!"',
    '"Minha visão já não é a mesma, então ler na tela era difícil. Este audiobook me permitiu escutar todas as ideias de preparação de refeições enquanto vou para o trabalho. Começar a minha reeducação alimentar agora ficou super simples!"',
    '"Eu estava em dúvida, mas as dicas diárias de nutrição são maravilhosas. Escutar o passo a passo sobre como preparar minhas marmitas da semana em áudio mudou minha organização de tempo. Recomendo muito!"',
    '"Minha visão já não é a mesma, então ler a tela do celular era difícil. Este Audiobook me permitiu fechar os olhos e simplesmente escutar as receitas proteicas. Surpreendentemente prático e fácil de aplicar!"',
    '"O conhecimento deste áudio vale cada centavo dos 29."',
    '"Fiquei em dúvida sobre adquirir o audiobook de forma isolada, mas o conteúdo é fantástico. Escutar as explicações de nutrição enquanto cozinho me ajudou imensamente a controlar a glicose de forma leve e sem esforço. Recomendo muito!"',
    '"Minha visão já não é a mesma, então ler na tela era difícil. Este audiobook me permitiu escutar os métodos práticos para cuidar do fígado. Cuidar da minha saúde agora ficou super simples!"',
    '"Eu estava em dúvida, mas as dicas do áudio são maravilhosas. Escutar as receitas recomendadas pela manhã mudou minha forma de me alimentar. Os níveis das minhas enzimas hepáticas até melhoraram!"',
    '"Minha visão já não é a mesma, então ler na tela era difícil. Este audiobook me permitiu descansar os olhos e apenas escutar os ensinamentos reais de nutrição. Cuidar do diabetes agora ficou super simples e prático!"',
    '"Eu estava em dúvida, mas as dicas diárias no grupo e os áudios são maravilhosos. Escutar as receitas em voz alta ao invés de ficar focado num manual logo mudou minha rotina na cozinha de forma positiva. Recomendo muito."',
    "© 2026 • Página de Pedido Segura • Política de Privacidade • Termos e Condições"
)

$fr_keys = @(
    'lang="fr"',
    '<title>Offre Exclusive</title>',
    "Commande presque terminée...",
    "Commande Presque Terminée...",
    "ATTENDEZ ! Votre commande n'est pas encore terminée...",
    'Obtenez le <span style="font-weight: 400;">Livre Audio</span>',
    "Recevez 3 Bonus Supplémentaires",
    "GRATUITEMENT !",
    "**Offre Spéciale Uniquement Pour Les Nouveaux Membres**",
    "Avant de finaliser votre commande, j'ai une petite question pour vous...",
    "Vous avez déjà obtenu notre guide complet qui vous montre exactement comment contrôler votre alimentation",
    ", sans renoncer aux aliments que vous aimez.",
    " après 60 ans",
    "Mais et si vous pouviez tout absorber plus facilement ? Et si vous pouviez littéralement <em>écouter</em> le guide où que vous alliez, sans avoir à forcer vos yeux ou à interrompre votre routine ?",
    "En ce moment, vous avez l'opportunité exclusive d'améliorer votre commande et d'obtenir la version complète en <strong>Livre audio de",
    "Au lieu de devoir trouver un moment de calme pour vous asseoir et lire, il vous suffit d'appuyer sur « lecture » et de commencer immédiatement à absorber ces directives transformatrices. Que vous vous détendiez dans votre fauteuil, que vous fassiez une douce promenade ou que vous vous occupiez des tâches ménagères...",
    "Tout le contenu est enregistré avec une narration professionnelle et agréable, afin que vous puissiez adopter le meilleur mode de vie sain sans aucun effort.",
    "V 100% Adapté aux Débutants & Conçu pour les Seniors",
    "Découvrez ce que vous obtenez pour seulement 29€ aujourd'hui :",
    "Écoutez n'importe où, n'importe quand. Parfait pour reposer vos yeux et absorber les connaissances sans stress.",
    "Bonus n° 1 : Communauté privée (Valeur 97€)",
    "Vous n'êtes pas seul(e). Bénéficiez d'un accès rapide pour échanger vos expériences avec d'autres personnes partageant les mêmes objectifs.",
    "Bonus n° 2 : Audios de Recettes Guidées (Valeur 147€)",
    "Écoutez pas à pas des recettes incroyables dans la cuisine, en étant guidé facilement tout au long du processus.",
    "Bonus n° 3 : Accès à vie à l'application (Valeur 19€/mois)",
    "Gardez tout votre guide dans votre poche. Facile à utiliser, super accessible et totalement GRATUIT aujourd'hui.",
    "Ceci est une offre unique.",
    "Dès que vous quitterez cette page, ces bonus disparaîtront et le Livre Audio reviendra à son prix normal de 197€.",
    "Puisque vous êtes nouveau ici, vous ajoutez ce forfait complet pour <strong>un seul paiement de 29€ !</strong>",
    "Garantie de Remboursement de 30 Jours",
    "Paiement sécurisé • Crypté",
    "Mise à jour vérifiée",
    "Page de commande sécurisée • Politique de Confidentialité • Termes et Conditions",
    "⚠️ NE FERMEZ PAS CETTE PAGE !",
    "Obtenez le Livre Audio Avec Une <span style=`"color: #B3200B; text-decoration: underline;`">Remise Exclusive</span> !",
    "Pour rendre cette offre irrésistible, <strong>j'ai supprimé l'accès à la communauté privée</strong> (ce qui réduit mes coûts) pour vous offrir le <strong>Livre Audio Complet des Recettes Protéinées + Audios de Recettes Pas à Pas</strong>...",
    "Pour rendre cette offre irrésistible, <strong>j'ai supprimé l'accès à la communauté privée</strong> (ce qui réduit mes coûts) pour vous offrir le <strong>Livre Audio Complet de Recettes & Meal Prep + Audios de Recettes Pas à Pas</strong>...",
    "Pour rendre cette offre irrésistible, <strong>j'ai supprimé l'accès à la communauté privée</strong> (ce qui réduit mes coûts) pour vous offrir le <strong>Livre Audio Complet pour Nettoyer le Foie + Audios de Recettes Pas à Pas</strong>...",
    "Pour rendre cette offre irrésistible, <strong>j'ai supprimé l'accès à la communauté privée</strong> (ce qui réduit mes coûts) pour vous offrir le <strong>Livre Audio Complet de Recettes pour le Diabète + Audios de Recettes Pas à Pas</strong>...",
    "Pour rendre cette offre irrésistible, <strong>j'ai supprimé l'accès à la communauté privée</strong> (ce qui réduit mes coûts) pour vous offrir le <strong>Livre Audio Complet du Régime + Audios de Recettes Pas à Pas</strong>...",
    "Pour un paiement unique de seulement 19€ !",
    "*Cliquez sur le bouton ci-dessous pour ajouter cette réduction immédiate à votre commande sécurisée.",
    '"Le livre audio a tout changé pour moi !"',
    '"Ma vue n''est plus la même, il m''était donc difficile de lire sur un écran. Ce livre audio m''a permis d''écouter des conseils pratiques sur la meilleure façon de cuisiner des protéines et des glucides. Préparer des repas est maintenant devenu très simple !"',
    '"Ces conseils valent chaque centime des 29€."',
    '"J''hésitais, mais les conseils quotidiens et les audios sont formidables. Écouter les recettes au lieu de les lire a changé ma routine. Les recettes riches en protéines m''ont donné beaucoup d''énergie !"',
    '"Ma vue n''est plus la même, lire sur un écran était difficile. Ce livre audio m''a permis d''écouter toutes les idées de préparation de repas sur le chemin du travail. Commencer ma rééducation alimentaire est devenu super simple !"',
    '"J''hésitais, mais les conseils nutritionnels quotidiens sont merveilleux. Écouter le pas à pas sur la façon de préparer mes repas de la semaine en audio a changé mon organisation de temps. Je recommande vivement !"',
    '"Ma vue n''est plus la même, lire sur l''écran du téléphone était difficile. Ce Livre Audio m''a permis de fermer les yeux et d''écouter simplement les recettes protéinées. Étonnamment pratique et facile à appliquer !"',
    '"Les connaissances de cet audio valent chaque centime des 29€."',
    '"J''hésitais à acheter le livre audio seul, mais le contenu est fantastique. Écouter les explications nutritionnelles en cuisinant m''a énormément aidé à contrôler ma glycémie de manière légère et sans effort. Je recommande vivement !"',
    '"Ma vue n''est plus la même, il m''était donc difficile de lire sur un écran. Ce livre audio m''a permis d''écouter des méthodes pratiques pour prendre soin de mon foie. Prendre soin de ma santé est maintenant devenu très simple !"',
    '"J''hésitais, mais les conseils audio sont formidables. Écouter les recettes recommandées le matin a changé ma façon de manger. Les niveaux de mes enzymes hépatiques se sont même améliorés !"',
    '"Ma vue n''est plus la même, il m''était donc difficile de lire sur un écran. Ce livre audio m''a permis de reposer mes yeux et d''écouter simplement de vrais enseignements nutritionnels. Gérer le diabète est maintenant devenu super simple et pratique !"',
    '"J''hésitais, mais les conseils quotidiens dans le groupe et les audios sont formidables. Écouter les recettes à voix haute au lieu de me concentrer sur un manuel a rapidement changé ma routine en cuisine de manière positive. Je recommande vivement."',
    "© 2026 • Page de Commande Sécurisée • Politique de Confidentialité • Termes et Conditions"
)

$path = "downdiabetesportugues\index.html"
$content = Get-Content $path -Raw -Encoding UTF8

for ($i = 0; $i -lt $fr_keys.Length; $i++) {
    $content = $content.Replace($fr_keys[$i], $pt_keys[$i])
}

# Specifc strings
$content = $content.Replace('"Ma vue n''est plus la même, lire sur l''écran du téléphone était difficile. Ce Livre Audio m''a permis de fermer les yeux et d''écouter simplement les conseils et les recettes pour diabétiques de la meilleure façon. Étonnamment pratique et facile à appliquer !"', '"Minha visão já não é a mesma, então ler a tela do celular era difícil. Este Audiobook me permitiu fechar os olhos e simplesmente escutar as dicas e receitas para diabéticos da melhor forma. Surpreendentemente prático e fácil de aplicar!"')
$content = $content.Replace('"Les audios guidés ont tout changé !"', '"Os áudios guiados mudaram tudo!"')

[System.IO.File]::WriteAllText($path, $content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Translated downdiabetesportugues back to Portuguese!"
